version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: oneday_diary
    volumes:
      - ./backend:/app

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: oneday_diary
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
